### ISSUE TITLE
Font Mastering

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/bilbo#1]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics
- [x] Caron.alt missing
- [x] Caron.alt glyphs need to be adjusted 

**Glyphs**
- [x] Missing glyphs: 0x00A0 (NO-BREAK SPACE), 0x2074 (SUPERSCRIPT FOUR), 0x2212 (MINUS SIGN) and 0x2215 (DIVISION SLASH)
- [x] Add extreme points

**OT Features**
- [ ] Ensure the OT features include everything and are working well (e.g. fi fl included)

**Comment by crystaltype** [comment]
> **Diacritics**
> 
> * [x]  Composite glyphs need to be made out of components using anchors
> * [x]  Comb.case are missing
> * [x]  Misaligned diacritics
> * [x]  Caron.alt missing
> * [x]  Caron.alt glyphs need to be adjusted
> 
> **Glyphs**
> 
> * [x]  Missing glyphs: 0x00A0 (NO-BREAK SPACE), 0x2074 (SUPERSCRIPT FOUR), 0x2212 (MINUS SIGN) and 0x2215 (DIVISION SLASH)
> * [x]  Add extreme points
> 
> **OT Features**
> 
> * [ ]  Ensure the OT features include everything and are working well (e.g. fi fl included)

**Comment by vv-monsalve** [comment]
@crystaltype when trying to generate the new font after merging the latest PR there was a new fontmake error:
`fontmake.errors.FontmakeError: In 'BilboPro.glyphs' -> 'master_ufo/BilboPro-Regular.designspace' -> 'master_ufo/instance_ufo/BilboPro-Regular.ufo': Compiling UFO failed: master_ufo/instance_ufo/BilboPro-Regular.ufo/features.fea:3:1884: The following glyph names are referenced but are missing from the glyph set: dotlessi`

Please remember to update the features every time you change a glyph name, particularly in cases where is not an automatically done one.

**Comment by vv-monsalve** [comment]
@crystaltype I've just pushed few new adjustments to Bilbo, please pull them before working on this project again.
